"""
Massive Stress Test: ~3000 examples
Comprehensive validation of the triviality gate
Run with: python massive_stress_test.py
"""

# Import the classifier
import sys
sys.path.insert(0, '.')

MASSIVE_TEST_CASES = []

# =========================================================================
# TRIVIAL EXAMPLES (~1500) - Should FLUSH
# =========================================================================

# Encyclopedic queries (200)
trivial_encyclopedic = [
    "What's the capital of France?", "How many continents are there?",
    "What year did World War 2 end?", "Who wrote Hamlet?",
    "What's the speed of light?", "How many bones in the human body?",
    "What's the largest planet?", "Who invented the lightbulb?",
    "What's the chemical symbol for gold?", "How many states in the US?",
    "What's the tallest mountain?", "Who painted the Sistine Chapel?",
    "What's the boiling point of water?", "How many feet in a mile?",
    "What's the smallest country?", "Who discovered penicillin?",
    "What's the atomic number of carbon?", "How many planets are there?",
    "Who was the first president?", "What's the longest river?",
    "How many teeth do adults have?", "Who wrote Pride and Prejudice?",
    "What's the capital of Japan?", "What year did the Titanic sink?",
    "Who invented the telephone?", "What's the largest ocean?",
    "How many days in a leap year?", "What's the currency of England?",
    "Who discovered gravity?", "What's the hardest natural substance?",
    "What's the capital of Australia?", "Who wrote 1984?",
    "What's the largest desert?", "How many sides does a hexagon have?",
    "What year did man land on the moon?", "Who invented the printing press?",
    "What's the deepest ocean?", "How many ounces in a pound?",
    "What's the capital of Brazil?", "Who painted the Mona Lisa?",
    "What's the largest mammal?", "How many seconds in an hour?",
    "What's the capital of Canada?", "Who wrote Romeo and Juliet?",
    "What's the fastest land animal?", "How many cups in a gallon?",
    "What's the capital of Germany?", "Who discovered America?",
    "What's the largest bird?", "How many inches in a foot?",
    "What's the capital of Italy?", "Who invented the airplane?",
    "What's the smallest bone in the body?", "How many degrees in a circle?",
    "What's the capital of Spain?", "Who wrote The Great Gatsby?",
    "What's the hottest planet?", "How many weeks in a year?",
    "What's the capital of Russia?", "Who invented electricity?",
    "What's the largest reptile?", "How many quarts in a gallon?",
    "What's the capital of China?", "Who wrote Moby Dick?",
    "What's the coldest continent?", "How many millimeters in a centimeter?",
    "What's the capital of India?", "Who discovered DNA?",
    "What's the largest fish?", "How many pints in a quart?",
    "What's the capital of Mexico?", "Who wrote War and Peace?",
    "What color are ladybugs?", "Why is the sky blue?",
    "How do magnets work?", "What makes rainbows?",
    "Why do leaves change color?", "How do planes fly?",
    "What causes earthquakes?", "Why is the ocean salty?",
    "How do birds migrate?", "What is photosynthesis?",
    "What's the square root of 144?", "How many legs does a spider have?",
    "What's the capital of Poland?", "Who discovered radium?",
    "What's the largest organ?", "How many hearts does an octopus have?",
    "What's the capital of Sweden?", "Who invented dynamite?",
    "What's the smallest planet?", "How many rings does Saturn have?",
    "What's the capital of Norway?", "Who wrote Crime and Punishment?",
    "How many moons does Mars have?", "What's the capital of Finland?",
    "Who invented the steam engine?", "What's the rarest blood type?",
    "What's the capital of Denmark?", "Who wrote Les Miserables?",
    "What's the most spoken language?", "How many bones in the spine?",
    "What's the capital of Belgium?", "Who invented vaccination?",
    "What's the longest bone?", "What's the capital of Austria?",
    "Who invented the microscope?", "What's the largest lake?",
    "What's the capital of Switzerland?", "Who wrote Frankenstein?",
    "What's the deepest lake?", "What's the capital of Portugal?",
    "Who invented the telescope?", "What's the capital of Ireland?",
    "Who wrote Dracula?", "What's the oldest civilization?",
    "What's the capital of New Zealand?", "Who invented the radio?",
    "What's the most expensive spice?", "What's the capital of Philippines?",
    "Who invented the battery?", "What's the oldest tree species?",
    "What's the capital of Thailand?", "Who wrote Ulysses?",
    "What's the fastest fish?", "What's the capital of Vietnam?",
    "What's the loudest animal?", "What's the capital of Malaysia?",
    "Who wrote Wuthering Heights?", "What's the most venomous snake?",
    "What's the capital of Singapore?", "Who invented the parachute?",
    "What's the largest spider?", "What's the capital of Indonesia?",
    "Who wrote Jane Eyre?", "What's the smallest mammal?",
    "What's the capital of Pakistan?", "Who invented the elevator?",
    "What's the oldest university?", "What's the capital of Bangladesh?",
    "What's the most populous city?", "What's the capital of Nigeria?",
    "What's the longest wall?", "What's the capital of Kenya?",
    "What's the driest place on Earth?", "What's the capital of Morocco?",
    "What's the wettest place on Earth?", "What's the capital of Algeria?",
    "What's the coldest place on Earth?", "What's the capital of Tunisia?",
    "What's the hottest place on Earth?", "What's the capital of Libya?",
    "What's the busiest airport?", "What's the capital of Ghana?",
    "What's the largest stadium?", "What's the capital of Senegal?",
    "What's the tallest building?", "What's the capital of Uganda?",
    "What's the longest bridge?", "What's the capital of Tanzania?",
    "What's the oldest parliament?", "What's the capital of Zimbabwe?",
    "What's the largest library?", "How many colors in a rainbow?",
    "What's the largest museum?", "How many countries in the UN?",
    "What's the oldest castle?", "How many keys on a piano?",
    "What's the largest church?", "How many strings on a guitar?",
    "What's the oldest bridge?", "How many cards in a deck?",
    "What's the largest mosque?", "How many squares on a chess board?",
    "What's the largest temple?", "How many dominoes in a set?",
    "What's the largest palace?", "How many tiles in Scrabble?",
]

# Weather / Small talk (200)
trivial_weather = [
    "Nice weather today", "It's pretty cold out", "Looks like rain",
    "The sun is really bright", "It's so humid", "Perfect day for a walk",
    "The wind is crazy today", "It might snow later", "What a beautiful sunset",
    "The clouds look interesting", "It's getting dark early", "Spring is finally here",
    "Summer flew by", "Fall is my favorite season", "Winter is coming",
    "The leaves are changing", "Cherry blossoms are out", "First day of spring",
    "Longest day of the year", "Shortest day of the year", "It's muggy out there",
    "The fog is thick", "There's frost on the ground", "The heat is unbearable",
    "Perfect beach weather", "Good day for staying inside", "The storm passed",
    "Thunder in the distance", "Lightning last night", "The rainbow was beautiful",
    "Hail damaged some cars", "The drought continues", "Finally some rain",
    "Roads are icy", "Schools closed for snow", "Power went out from the storm",
    "Wildfire smoke in the air", "Air quality is bad today", "Pollen count is high",
    "My weather app was wrong", "The forecast keeps changing", "Unseasonably warm",
    "Unseasonably cold", "Record high temperature today", "Weird weather patterns",
    "How about this weather", "Can you believe this heat", "I miss summer already",
    "Ready for winter to be over", "The days are getting longer", "The days are getting shorter",
    "Daylight saving time is stupid", "The moon was huge last night", "Full moon tonight",
    "Stars are bright tonight", "Meteor shower this week", "The sky is so clear",
    "Too cloudy to see anything", "Breeze feels nice", "Wind chill is brutal",
    "Heat index over 100", "Dry heat is better", "Humid heat is worse",
    "I prefer cold to hot", "I prefer hot to cold", "Sweater weather",
    "T-shirt weather", "Jacket weather", "Umbrella day", "Sunglasses day",
    "Morning fog burned off", "Afternoon thunderstorms likely", "Temperature dropping tonight",
    "Warming trend this week", "Cooling trend coming", "Chance of precipitation",
    "Partly cloudy skies", "Mostly sunny", "Overcast all day",
    "Storm front approaching", "Cold front tonight", "Warm front moving through",
    "Freezing rain tonight", "Wintry mix expected", "Lake effect snow",
    "Beach conditions perfect", "Water temperature cold", "Pool weather finally",
    "Too cold to swim", "Great hiking weather", "Bad day for outdoor activities",
    "The barometer is dropping", "Humidity is awful", "Such a nice breeze",
    "The air smells like rain", "Thunder woke me up", "Beautiful morning",
    "Gorgeous evening", "Perfect picnic weather", "Stay hydrated",
    "Bundle up out there", "Don't forget sunscreen", "Bring a jacket",
    "Might need an umbrella", "Check the forecast", "Weather looks good",
    "Weather looks bad", "Storm warning", "Flood watch", "Heat advisory",
    "Freeze warning", "Wind advisory", "Dense fog advisory", "Air quality alert",
    "Red flag warning", "Winter weather advisory", "Tornado watch",
    "Hurricane warning", "Severe thunderstorm warning", "Tropical storm approaching",
    "Eye of the hurricane", "Storm surge expected", "Evacuation orders",
    "Shelter in place", "Power outages expected", "Road closures likely",
    "Flight delays expected", "Travel not recommended", "Stay safe out there",
    "Check on your neighbors", "Stock up on supplies", "Charge your devices",
    "Fill up your gas tank", "Get emergency kit ready", "Know your evacuation route",
    "Weather will improve", "Clearing by tomorrow", "Nice weekend ahead",
    "Rainy week coming", "Cold snap approaching", "Heat wave expected",
    "Indian summer", "False spring", "Late season snow",
    "Early frost", "Unseasonable warmth", "Weather whiplash",
    "Can't dress for this weather", "Wore the wrong thing today",
    "Should have checked the weather", "Weather changed suddenly",
    "Didn't expect this rain", "Caught without an umbrella",
    "Got sunburned", "Got soaked", "Froze my butt off",
    "Sweating through my shirt", "Hair is ruined from humidity",
    "Weather ruined my plans", "Rescheduled due to weather",
    "Canceled because of the storm", "Weather delay",
]

# Random observations / idle chatter (200)
trivial_observations = [
    "That's a nice car", "Cool shirt", "I like your shoes",
    "Interesting building", "The food was okay", "This coffee is strong",
    "The music is loud", "Traffic was bad", "The line is long",
    "This place is crowded", "The service was slow", "The wifi is terrible",
    "My battery is dying", "I need to charge my phone", "The app crashed",
    "My computer is slow", "The printer is jammed", "The elevator is slow",
    "The stairs are faster", "The door is stuck", "The AC is too cold",
    "The heat is too high", "The lights are dim", "The TV is too loud",
    "The fridge is humming", "The washing machine is done", "The dryer takes forever",
    "The sink is clogged", "The toilet is running", "The shower pressure is weak",
    "The garbage disposal jammed", "The recycling is full", "The trash needs to go out",
    "The lawn needs mowing", "The garden needs weeding", "The fence needs fixing",
    "The garage is a mess", "The closet is full", "The drawer is stuck",
    "The shelf is crooked", "The picture is tilted", "The mirror is smudged",
    "The window is dirty", "The carpet needs vacuuming", "The floor needs mopping",
    "The table is sticky", "The chair is wobbly", "The couch is uncomfortable",
    "The bed is too soft", "The pillow is flat", "The blanket is scratchy",
    "The sheets need changing", "The towels are rough", "The soap is almost gone",
    "The toothpaste is running low", "The light bulb burned out", "The batteries are dead",
    "The remote isn't working", "The clock is wrong", "The pen is out of ink",
    "The scissors are dull", "The tape is gone", "The glue dried up",
    "The stapler is empty", "The package arrived", "The mail is late",
    "The store is out of stock", "The sale ended yesterday", "The coupon expired",
    "The price went up", "The cashier was slow", "The bag ripped",
    "The parking lot was full", "The gas station was crowded", "The car needs gas",
    "The tire looks low", "The oil needs changing", "The wipers are streaky",
    "The headlight is out", "The brakes are squeaky", "The engine sounds weird",
    "The GPS is outdated", "The Bluetooth won't connect", "The charger is missing",
    "The sunglasses are scratched", "My coat needs dry cleaning", "These pants don't fit",
    "This shirt is wrinkled", "My socks don't match", "I lost a button",
    "The zipper is stuck", "Need new shoes", "These are comfortable",
    "That color looks good", "This material is nice", "Good quality",
    "Cheaply made", "Falls apart fast", "Lasts forever",
    "Worth the price", "Overpriced", "Good deal",
    "Bad value", "Should have waited for a sale", "Impulse buy",
    "Needed it anyway", "Didn't need it", "Useful",
    "Useless", "Takes up space", "Perfect size",
    "Too big", "Too small", "Just right",
    "Wrong color", "Different in person", "Looks like the picture",
    "Better than expected", "Worse than expected", "As expected",
    "Would buy again", "Would not recommend", "Five stars",
    "One star", "Mixed reviews", "Read the reviews first",
    "Didn't read the reviews", "Should have researched more", "Did my homework",
    "Good brand", "Bad brand", "Never heard of them",
    "Popular choice", "Hidden gem", "Mainstream",
    "Unique find", "Common everywhere", "Hard to find",
    "Back in stock", "Sold out again", "Limited edition",
    "Regular version", "Special release", "Collector's item",
    "Mass produced", "Handmade", "Vintage",
    "Brand new", "Slightly used", "Like new",
    "Well worn", "Needs repair", "Broken",
    "Still works", "Barely works", "Works great",
    "Updated version", "Old model", "Latest release",
    "Discontinued", "Classic design", "Modern look",
    "Retro style", "Minimalist", "Maximalist",
    "Practical", "Decorative", "Both",
    "Neither", "Subjective", "Objective",
]

# Preferences / opinions (200)
trivial_preferences = [
    "I prefer tea over coffee", "Cats are better than dogs", "Dogs are more loyal",
    "I like summer better", "Winter has its charm", "Fall is underrated",
    "Mountains over beaches", "Beaches are more relaxing", "City life is exciting",
    "Country life is peaceful", "Suburbs are boring", "I'm a morning person",
    "I'm a night owl", "Coffee helps me function", "Tea is more civilized",
    "Soda is too sweet", "Water is best", "I don't like spicy food",
    "The spicier the better", "Hot sauce on everything", "Ketchup is overused",
    "Mustard is underrated", "Ranch goes on everything", "I prefer sweet over savory",
    "Brunch is the best meal", "Dessert is unnecessary", "Chocolate over vanilla",
    "Vanilla is not boring", "Cookie dough is the best", "Plain is fine",
    "Less is more", "Quality over quantity", "Bigger is better",
    "I like things organized", "Mess means creativity", "Clean space clean mind",
    "Minimalism is appealing", "Neutral colors are calming", "Bright colors are energizing",
    "Black goes with everything", "White shows dirt", "Gray is boring",
    "Red is too bold", "Blue is calming", "Green is refreshing",
    "Yellow is cheerful", "Purple is regal", "Matte over glossy",
    "Old things have soul", "New things work better", "Vintage is cool",
    "Modern is cleaner", "Classic never goes out of style", "Easy is underrated",
    "Hard work pays off", "Balance is key", "Rules exist for a reason",
    "Consistency is important", "Flexibility is valuable", "Pick your battles",
    "Communication is key", "Actions speak louder", "Words matter too",
    "Silence is golden", "Listen more than you talk", "Trust but verify",
    "First impressions matter", "People can change", "Context is everything",
    "Nuance is important", "Simple is hard", "Good enough is sometimes enough",
    "Perfect is the enemy of good", "Routines help", "Variety is the spice of life",
    "Rest is productive", "Ambition is healthy", "Contentment is underrated",
    "Gratitude helps", "Comparison is the thief of joy", "Community matters",
    "Boundaries are healthy", "Pineapple on pizza is controversial", "Books are better than movies",
    "The original is always better", "Sequels are usually worse", "Audiobooks count as reading",
    "Physical books are better", "E-readers are convenient", "Hardcover over paperback",
    "Used books have character", "Libraries are underrated", "Online shopping is easier",
    "In-store is more fun", "Cash is king", "Cards are more convenient",
    "Budgeting is important", "Saving matters", "Experiences over things",
    "Practicality wins", "Aesthetics matter", "Function over form",
    "Form follows function", "Design matters", "Engineering matters more",
    "Both are important", "Depends on the context", "Case by case basis",
    "No absolutes", "Some absolutes", "Moral relativism is tricky",
    "Ethics are complicated", "Common sense isn't common", "Logic prevails",
    "Emotion has its place", "Intuition is underrated", "Data driven decisions",
    "Trust your gut", "Second opinions help", "Too many cooks",
    "Collaboration is key", "Individual work is better", "Hybrid approach",
    "Remote work is great", "Office has its benefits", "Flexibility is best",
    "Structure helps", "Freedom is important", "Autonomy matters",
    "Guidance is needed", "Self directed learning", "Structured curriculum",
    "Both work", "Depends on the person", "Know yourself",
    "Growth mindset", "Fixed traits exist", "Nature and nurture",
    "Environment shapes us", "Genetics matter", "We make choices",
    "Determinism is depressing", "Free will is comforting", "Compatibilism works",
    "Philosophy is interesting", "Philosophy is pointless", "It depends",
    "Everything is relative", "Some things are absolute", "Truth is complicated",
    "Honesty is best", "White lies are okay", "Context matters",
    "Always tell the truth", "Protect feelings sometimes", "Be diplomatic",
    "Be direct", "Read the room", "Adapt your style",
    "Be consistent", "Be flexible", "Know when to bend",
    "Stand your ground", "Pick your battles wisely", "Everything is a battle",
    "Nothing is worth fighting for", "Some things are", "Figure out what",
    "Values matter", "Principles guide", "Rules are guidelines",
    "Guidelines are rules", "It's complicated", "Keep it simple",
    "Embrace complexity", "Reduce complexity", "Necessary complexity",
    "Unnecessary complexity", "Elegant solutions", "Brute force works",
]

# How-to questions (200)
trivial_howto = [
    "How do I tie a tie?", "What's the best way to cook rice?",
    "How long do I boil an egg?", "What temperature for chicken?",
    "How do I change a tire?", "How do I clean windows?",
    "How do I remove a stain?", "How do I fold a fitted sheet?",
    "How do I unclog a drain?", "How do I sharpen a knife?",
    "How do I parallel park?", "What's the formula for area of a circle?",
    "How do I calculate a tip?", "What's 20% of this?",
    "How do I convert Celsius to Fahrenheit?", "What's the metric equivalent?",
    "How do I say hello in French?", "What does this word mean?",
    "How do I spell that?", "What's the plural of octopus?",
    "How do I use a semicolon?", "What's the difference between its and it's?",
    "How do I cite a source?", "How do I write a cover letter?",
    "What should a resume include?", "How do I take a screenshot?",
    "What's the shortcut for copy?", "How do I clear my cache?",
    "What browser is best?", "How do I update my software?",
    "How do I check my storage?", "How do I speed up my computer?",
    "How do I fix a frozen screen?", "How do I recover a deleted file?",
    "How do I empty the trash?", "How do I organize my files?",
    "How do I backup my data?", "How do I share a file?",
    "How do I shorten a URL?", "What's a QR code?",
    "How do I scan one?", "How do I download that?",
    "How do I update my apps?", "How do I change my settings?",
    "How do I reset to factory?", "How do I transfer my data?",
    "How do I connect Bluetooth?", "How do I find the password?",
    "How do I change my password?", "How do I enable two factor?",
    "How do I recover my account?", "How do I contact support?",
    "How do I make an appointment?", "What documents do I need?",
    "How do I fill out this form?", "How do I submit?",
    "What's the deadline?", "How do I check my status?",
    "How do I track my order?", "How do I return this?",
    "What's the return policy?", "How do I get a refund?",
    "How long does it take?", "What's the fee?",
    "How do I avoid that?", "How do I qualify?",
    "What are the requirements?", "How do I apply?",
    "What's the next step?", "How do I prepare?",
    "What should I expect?", "How does it work?",
    "How do I cancel?", "What's the penalty?",
    "How do I opt out?", "What are my options?",
    "How do I choose?", "What's recommended?",
    "How do I compare?", "What's the difference?",
    "What's better?", "What sources are reliable?",
    "How do I verify?", "What are the signs?",
    "How do I recognize?", "How do I avoid scams?",
    "What are red flags?", "How do I report?",
    "How do I document?", "How do I remember?",
    "How do I stay organized?", "What tools help?",
    "How do I start?", "What's first?",
    "Where do I begin?", "What's the process?",
    "How do I make coffee?", "How do I brew tea?",
    "How do I bake cookies?", "How do I make bread?",
    "How do I grill steak?", "How do I roast vegetables?",
    "How do I make soup?", "How do I make salad dressing?",
    "How do I poach an egg?", "How do I make pancakes?",
    "How do I whip cream?", "How do I melt chocolate?",
    "How do I caramelize onions?", "How do I sear meat?",
    "How do I deglaze a pan?", "How do I make gravy?",
    "How do I thicken sauce?", "How do I reduce liquid?",
    "How do I blanch vegetables?", "How do I steam fish?",
    "How do I fry chicken?", "How do I bake fish?",
    "How do I make rice pilaf?", "How do I cook quinoa?",
    "How do I prepare lentils?", "How do I soak beans?",
    "How do I make hummus?", "How do I make guacamole?",
    "How do I make salsa?", "How do I make pesto?",
    "How do I knead dough?", "How do I proof yeast?",
    "How do I roll pie crust?", "How do I crimp edges?",
    "How do I temper chocolate?", "How do I pipe frosting?",
    "How do I level a cake?", "How do I frost a cake?",
    "How do I decorate cookies?", "How do I make royal icing?",
    "How do I use a piping bag?", "How do I make meringue?",
    "How do I fold egg whites?", "How do I make custard?",
    "How do I make pudding?", "How do I set gelatin?",
    "How do I make jam?", "How do I can vegetables?",
    "How do I pickle cucumbers?", "How do I ferment sauerkraut?",
    "How do I make kombucha?", "How do I brew beer?",
    "How do I make wine?", "How do I infuse spirits?",
    "How do I make cocktails?", "How do I muddle mint?",
    "How do I rim a glass?", "How do I shake vs stir?",
    "How do I layer drinks?", "How do I garnish?",
    "How do I open wine?", "How do I decant wine?",
    "How do I store wine?", "How do I serve cheese?",
    "How do I pair wine and cheese?", "How do I taste wine?",
    "How do I describe wine?", "What's a good vintage?",
    "How do I read a wine label?", "How do I choose wine?",
    "How do I order wine?", "How do I send wine back?",
    "How do I tip at a restaurant?", "How do I split a check?",
    "How do I make a reservation?", "How do I dress for dinner?",
    "How do I use chopsticks?", "How do I eat sushi?",
    "How do I order at a sushi bar?", "What's omakase?",
    "How do I eat with my hands?", "What's the etiquette?",
    "How do I set a table?", "How do I fold napkins?",
    "How do I serve food?", "How do I clear plates?",
    "How do I wash dishes?", "How do I load a dishwasher?",
    "How do I clean cast iron?", "How do I season cast iron?",
    "How do I store knives?", "How do I sharpen knives?",
    "How do I organize a kitchen?", "How do I meal prep?",
]

# Greetings and generic (200)
trivial_greetings = [
    "Can you help me with something?", "I have a question", "Quick question",
    "Just curious", "Random thought", "I was wondering",
    "Do you know", "Any idea", "What do you think",
    "Is it true that", "I heard that", "Someone told me",
    "They say that", "People say", "Everyone knows",
    "Obviously", "Clearly", "Apparently",
    "Probably", "Maybe", "Perhaps",
    "Possibly", "Likely", "Depends",
    "It varies", "It's complicated", "Long story short",
    "Bottom line", "In summary", "All things considered",
    "At the end of the day", "In theory", "In practice",
    "On paper", "In reality", "Ideally",
    "Realistically", "Technically", "Generally speaking",
    "Specifically", "In particular", "Especially",
    "Notably", "Importantly", "Essentially",
    "Basically", "Simply put", "In other words",
    "What I mean is", "To be clear", "For the record",
    "For what it's worth", "FYI", "Just so you know",
    "Heads up", "By the way", "On a side note",
    "Speaking of which", "Regarding", "About that",
    "Good question", "Great question", "Valid point",
    "Good point", "True", "That's true",
    "You're right", "Correct", "Exactly",
    "Indeed", "Absolutely", "Definitely",
    "Certainly", "Of course", "Sure",
    "Yeah", "Yep", "Right",
    "Okay", "OK", "Alright",
    "Got it", "I see", "I understand",
    "Makes sense", "Fair enough", "Noted",
    "Understood", "Will do", "No problem",
    "No worries", "All good", "Sounds good",
    "Works for me", "That's fine", "Whatever works",
    "Up to you", "Your call", "I don't mind",
    "Either way", "No preference", "Flexible",
    "Let me know", "Keep me posted", "Talk soon",
    "Later", "See you", "Take care",
    "Bye", "Hey", "Hi",
    "Hello", "What's up", "How's it going",
    "How are you", "Good morning", "Good afternoon",
    "Good evening", "Good night", "Nice to meet you",
    "Pleasure", "Thanks", "Thank you",
    "Appreciate it", "You're welcome", "No problem at all",
    "Happy to help", "Anytime", "My pleasure",
    "Don't mention it", "Sure thing", "Cheers",
    "Best wishes", "Warm regards", "Kind regards",
    "Sincerely", "Respectfully", "Cordially",
    "Best", "Thanks again", "Much appreciated",
    "Grateful", "Thankful", "Blessed",
    "Lucky", "Fortunate", "Happy",
    "Glad", "Pleased", "Delighted",
    "Thrilled", "Excited", "Looking forward",
    "Can't wait", "Eager", "Ready",
    "Prepared", "Set", "Good to go",
    "All set", "Ready when you are", "At your convenience",
    "Whenever works", "No rush", "Take your time",
    "Whenever you can", "At your earliest", "ASAP",
    "Urgent", "Not urgent", "Low priority",
    "High priority", "Important", "Critical",
    "Trivial", "Minor", "Major",
    "Significant", "Insignificant", "Meaningful",
    "Meaningless", "Relevant", "Irrelevant",
    "Useful", "Useless", "Helpful",
    "Unhelpful", "Productive", "Unproductive",
    "Efficient", "Inefficient", "Effective",
    "Ineffective", "Successful", "Unsuccessful",
    "Complete", "Incomplete", "Done",
    "Not done", "Finished", "Unfinished",
    "Started", "Not started", "In progress",
    "On hold", "Delayed", "On track",
    "Ahead of schedule", "Behind schedule", "On time",
    "Late", "Early", "Punctual",
]

# Food / entertainment (100)
trivial_entertainment = [
    "That movie was good", "The sequel was worse", "I binged that show",
    "The ending was weird", "No spoilers please", "The book was better",
    "Great performance though", "The soundtrack was amazing", "That song is stuck in my head",
    "Their old stuff was better", "That concert was incredible", "Tickets were expensive",
    "The game was intense", "We lost in overtime", "The ref made a bad call",
    "What an upset", "Fantasy football is stressful", "My team is doing well",
    "This recipe is easy", "I burned dinner", "The pasta is overcooked",
    "Needs more salt", "The steak is perfect", "Medium rare is the only way",
    "The chicken is dry", "Should have brined it", "The bread didn't rise",
    "The cake is dense", "The cookies spread too much", "Restaurant quality",
    "Better than takeout", "Should have ordered in", "The delivery was fast",
    "The food was cold", "The order was wrong", "The portions are huge",
    "I need a box", "Leftovers for tomorrow", "Cast iron is worth it",
    "Nonstick is easier", "Sharp knife matters", "Prep everything first",
    "Read the recipe through", "Season to taste", "Butter makes it better",
    "More cheese", "Never enough bacon", "I ordered sushi",
    "Pizza night", "Taco Tuesday", "Wing Wednesday",
    "Thirsty Thursday", "Fish Friday", "Saturday brunch",
    "Sunday roast", "Meal prep Sunday", "Leftover Monday",
    "New recipe Tuesday", "Comfort food Wednesday", "Light salad Thursday",
    "Treat yourself Friday", "Date night dinner", "Family dinner",
    "Potluck", "BBQ", "Picnic",
    "Cookout", "Dinner party", "Happy hour",
    "Brunch date", "Coffee date", "Lunch meeting",
    "Business dinner", "Working lunch", "Quick bite",
    "Full meal", "Light snack", "Heavy appetizer",
    "Small plates", "Family style", "Prix fixe",
    "Tasting menu", "Chef's table", "Bar seating",
    "Patio dining", "Indoor seating", "Private room",
    "Reservation required", "Walk-ins welcome", "Wait time",
    "Worth the wait", "Not worth the wait", "Overhyped",
    "Underrated", "Hidden gem", "Tourist trap",
    "Local favorite", "Chain restaurant", "Mom and pop shop",
    "Fine dining", "Casual dining", "Fast casual",
    "Fast food", "Food truck", "Pop up",
    "Ghost kitchen", "Delivery only", "Dine in only",
    "Takeout available", "Curbside pickup", "Drive through",
]

# Add all trivial to the list
for item in trivial_encyclopedic:
    MASSIVE_TEST_CASES.append((item, "flush"))
for item in trivial_weather:
    MASSIVE_TEST_CASES.append((item, "flush"))
for item in trivial_observations:
    MASSIVE_TEST_CASES.append((item, "flush"))
for item in trivial_preferences:
    MASSIVE_TEST_CASES.append((item, "flush"))
for item in trivial_howto:
    MASSIVE_TEST_CASES.append((item, "flush"))
for item in trivial_greetings:
    MASSIVE_TEST_CASES.append((item, "flush"))
for item in trivial_entertainment:
    MASSIVE_TEST_CASES.append((item, "flush"))

# =========================================================================
# MEANINGFUL EXAMPLES (~1500) - Should PERSIST
# =========================================================================

meaningful_emotional = [
    "I've been feeling really down lately", "I can't shake this sadness",
    "Everything feels hopeless", "I don't see the point anymore",
    "Life feels meaningless", "I'm struggling to find joy",
    "Nothing makes me happy", "I feel empty inside",
    "There's a void I can't fill", "I'm emotionally numb",
    "I can't feel anything", "My emotions are all over the place",
    "I cry for no reason", "The tears won't stop",
    "I haven't cried in years", "I wish I could cry",
    "Bottling everything up", "I'm about to explode",
    "My anger scares me", "I have rage issues",
    "I can't control my temper", "I've been lashing out",
    "I hurt people I love when I'm angry", "I say things I don't mean",
    "The guilt is eating me alive", "I can't forgive myself",
    "I hate who I've become", "I don't recognize myself anymore",
    "I've lost myself", "I don't know who I am",
    "I'm having an existential crisis", "What's my purpose",
    "I feel purposeless", "I'm drifting through life",
    "Just going through the motions", "I'm on autopilot",
    "I'm barely surviving", "I'm hanging on by a thread",
    "I'm at the end of my rope", "I don't know how much more I can take",
    "I'm at my breaking point", "I'm burned out completely",
    "I have nothing left to give", "I'm running on empty",
    "I'm exhausted to my core", "The fatigue is overwhelming",
    "I can't sleep", "I sleep too much",
    "Sleep is my escape", "I dread waking up",
    "Mornings are the hardest", "Night time anxiety hits different",
    "The thoughts won't stop at night", "Racing thoughts keep me up",
    "My mind won't shut off", "I'm constantly overthinking",
    "I worry about everything", "The anxiety is constant",
    "I'm always on edge", "I can't relax",
    "My body is tense all the time", "Panic attacks are debilitating",
    "I thought I was dying", "My heart was racing",
    "I couldn't breathe", "The walls were closing in",
    "I had to leave immediately", "I avoid certain places now",
    "My world is getting smaller", "I barely leave the house",
    "Social situations terrify me", "I'm scared of being judged",
    "Everyone is looking at me", "I feel like a fraud",
    "Imposter syndrome is real", "I don't deserve my success",
    "I'm waiting to be found out", "I don't belong here",
    "I've never fit in anywhere", "I'm always the outsider",
    "I don't have real friends", "People tolerate me",
    "Nobody actually likes me", "I'm a burden to everyone",
    "People would be better off without me", "I've thought about disappearing",
    "I've had dark thoughts", "I've thought about hurting myself",
    "I used to self harm", "I've relapsed",
    "The urges are back", "I'm scared of myself",
    "I don't trust myself alone", "I need help",
    "I'm finally admitting I need help", "I started therapy",
    "Therapy is hard but helping", "My therapist challenged me today",
    "I had a breakthrough", "I'm processing trauma",
    "EMDR is intense", "I remembered something I blocked",
    "The memories came flooding back", "I didn't know I had PTSD",
    "Triggers are everywhere", "I got triggered today",
    "Flashbacks are terrifying", "I dissociated",
    "I lose time sometimes", "I don't remember chunks of my life",
    "My childhood is a blur", "I blocked out the bad parts",
    "My mind protected me", "I question my memories",
    "I minimize what happened", "My trauma isn't valid",
    "I gaslight myself", "My parents did their best",
    "Their best wasn't enough", "I'm angry at them",
    "I'm grieving the childhood I didn't have", "I raised myself",
    "I was parentified", "I took care of everyone else",
    "No one took care of me", "I never learned to self soothe",
    "I have unhealthy coping mechanisms", "I'm aware of my patterns",
    "Breaking the cycle is hard", "I don't want to repeat their mistakes",
    "The generational trauma stops with me", "I'm trying to heal",
    "Healing isn't linear", "I had a setback",
    "Progress feels slow", "Self compassion is hard",
    "I'm my own worst critic", "The inner voice is cruel",
    "I need to be kinder to myself", "I'm learning to love myself",
    "I've always hated myself", "The self loathing runs deep",
    "Something is wrong with me", "I feel broken",
    "I feel defective", "I never asked for this",
    "I didn't choose this brain", "Mental illness runs in my family",
    "I'm medicated now", "The meds help",
    "The meds have side effects", "Finding the right combo is hard",
    "I'm treatment resistant", "Nothing seems to work",
    "I just want to feel normal", "I've been sick for so long",
    "I mourn who I could have been", "The illness stole years",
    "I feel behind in life", "Everyone else has it together",
    "I'm tired of pretending", "I hide how I really feel",
    "No one knows the real me", "I'm scared to be vulnerable",
    "I was taught to be strong", "Strong meant silent",
    "I was never allowed to feel", "I shut down my emotions",
    "I want to feel again", "I'm learning it's okay to feel",
    "All emotions are valid", "I'm allowed to struggle",
    "Asking for help is strength", "I can't do this alone",
    "I need support", "I'm building a support system",
    "I found my people", "Group therapy helps",
    "I'm not as alone as I thought", "I feel seen",
    "I feel heard", "I just want to be understood",
]

meaningful_family = [
    "My parents are getting divorced", "The divorce is messy",
    "I'm caught in the middle", "They use me as a messenger",
    "I have to pick sides", "I love both of them",
    "This isn't my fault", "The house was always tense",
    "Walking on eggshells", "I became hypervigilant",
    "I was the peacekeeper", "I tried to fix everything",
    "That wasn't my job", "I was a child",
    "They leaned on me too much", "I was my mother's therapist",
    "They told me things I shouldn't know", "I grew up too fast",
    "I never got to be a kid", "I was responsible for my siblings",
    "I raised them more than my parents did", "I sacrificed my childhood",
    "I resent them sometimes", "Our relationship is complicated",
    "We're not close anymore", "We grew apart",
    "We only have trauma in common", "We remember things differently",
    "They deny what happened", "Gaslighting from family is the worst",
    "I know what I experienced", "I've set boundaries",
    "They don't respect my boundaries", "They call me dramatic",
    "They say I'm too sensitive", "They say I've changed",
    "Growth looks like change", "They preferred the old me",
    "Now I advocate for myself", "I broke the cycle",
    "They're punishing me for it", "I'm the black sheep now",
    "I've always been different", "I stopped trying to fit",
    "They can accept me or not", "Losing family is painful",
    "Chosen family is real family", "I've built my own family",
    "My friends are my family", "Blood isn't everything",
    "I was alone in hard times", "I learned to rely on myself",
    "I struggle to trust", "My trust was broken young",
    "The people who should have protected me didn't", "I protected myself",
    "Hyperindependence is a trauma response", "I'm learning to lean on others",
    "I want deep connection", "I crave authenticity",
    "I want to be truly known", "Who could love all of me",
    "I'm more than my trauma", "Making peace with my past",
    "My relationship is struggling", "We're not communicating well",
    "We've grown apart", "We want different things",
    "I'm not sure we're compatible", "I love them but",
    "Love isn't always enough", "We're in couples therapy",
    "I don't know if it can be saved", "I'm scared to leave",
    "I'm scared to stay", "I don't want to start over",
    "I deserve better", "I question my worth",
    "I've dated toxic people", "I see the pattern now",
    "I recreate my childhood dynamics", "I need to heal myself first",
    "I'm not ready for a relationship", "I'm working on me",
    "Healthy love exists", "My spouse passed away",
    "I'm a widow now", "The grief is unbearable",
    "I lost my person", "We had so many plans",
    "I don't know who I am without them", "Starting over at this age",
    "The house is so quiet", "I still feel their presence",
    "Sometimes I forget they're gone", "Grief comes in waves",
    "Anniversaries are painful", "We had a baby",
    "I'm a new parent", "I'm terrified of messing this up",
    "I don't want to repeat my parents mistakes", "Nobody prepares you for this",
    "The love is overwhelming", "I worry constantly",
    "I want to protect them from everything", "My kid is struggling",
    "They're being bullied", "My heart breaks for them",
    "I feel helpless", "My child came out to me",
    "I'm proud of them", "I love them no matter what",
    "I support them fully", "I'm estranged from my adult children",
    "I made mistakes", "I wish I could go back",
    "I hope we can reconcile", "I miss them every day",
    "I respect their boundaries", "My dad died yesterday",
    "My mom passed last month", "I lost my brother",
    "My sister is gone", "I miss my grandparents",
    "I never said goodbye", "I regret so much",
    "The last conversation haunts me", "I wish I'd called more",
    "I wish I'd visited more", "Now it's too late",
    "I'm dealing with the estate", "Family is fighting over inheritance",
    "Money ruins families", "I just want peace",
    "I just want us to be okay", "We'll never be the same",
    "The holidays are hard now", "Their chair is empty",
    "I set a place anyway", "Traditions feel hollow",
    "I'm making new traditions", "For my kids",
    "They deserve happy memories", "Not the dysfunction I had",
]

meaningful_identity = [
    "I'm neurodivergent", "I have ADHD",
    "I'm on the autism spectrum", "I have dyslexia",
    "I process things differently", "My brain works differently",
    "I've learned to adapt", "Masking is exhausting",
    "I mask all day at work", "Then I crash when I get home",
    "Autistic burnout is real", "ADHD burnout is real",
    "I need to unmask more", "I need to find my people",
    "Other neurodivergent folks get it", "I finally feel understood",
    "Late diagnosis changed everything", "It explained so much",
    "I grieved the earlier diagnosis I could have had", "I'm not broken just different",
    "Different not less", "I'm learning to embrace it",
    "I'm LGBTQ", "I'm gay",
    "I'm lesbian", "I'm bisexual",
    "I'm transgender", "I'm nonbinary",
    "I'm questioning my identity", "Coming out was hard",
    "Not everyone accepted me", "I lost some people",
    "I gained my true self", "Living authentically matters more",
    "I'm finally myself", "I wasted years hiding",
    "I'm finding community", "Queer joy is real",
    "I'm proud of who I am", "It took time to get here",
    "Internalized shame ran deep", "Some days are still hard",
    "The world isn't always safe", "I have to be careful",
    "I can't be out everywhere", "I dream of a world where I can just exist",
    "I'm an immigrant", "I came to this country as a child",
    "I'm a refugee", "I fled my country",
    "I saw things no one should see", "I lost everything",
    "I rebuilt from nothing", "I miss my homeland",
    "I can never go back", "My family is scattered",
    "I don't know if they're safe", "Survivor's guilt is heavy",
    "I work harder than anyone", "I have to prove I belong",
    "I'm caught between cultures", "Third culture kid",
    "I don't fully belong anywhere", "I'm a first generation student",
    "First in my family to go to college", "I didn't have guidance",
    "I figured it out alone", "I didn't know the unwritten rules",
    "I'm proof it's possible", "I grew up poor",
    "We didn't have much", "I know what hunger feels like",
    "I know what cold feels like", "We lost our housing",
    "I experienced homelessness", "I lived in my car",
    "Rock bottom was real", "I climbed out",
    "Money anxiety never fully leaves", "Scarcity mindset is hard to shake",
    "I have a disability", "I'm physically disabled",
    "I use a wheelchair", "I use mobility aids",
    "I'm visually impaired", "I'm deaf",
    "I have chronic illness", "I have an invisible disability",
    "People don't see my struggles", "I look fine on the outside",
    "I pace myself carefully", "Spoon theory is my life",
    "I've had to accept limitations", "I grieved my able body",
    "I'm more than my disability", "Accessibility matters",
    "The world isn't built for me", "I have to advocate constantly",
    "I'm a veteran", "I served in the military",
    "I saw combat", "I lost friends over there",
    "I came back different", "Adjusting to civilian life is hard",
    "People don't understand", "The nightmares continue",
    "Certain sounds trigger me", "I'm hypervigilant always",
    "Fellow vets understand", "I'm a survivor",
    "I survived abuse", "I survived assault",
    "I'm still here", "I'm more than what happened to me",
    "I'm reclaiming my story", "I'm a recovering addict",
    "I'm in recovery", "Sobriety is a daily choice",
    "Every day counts", "One day at a time",
    "I've relapsed before", "I got back up",
    "I keep getting back up", "The program helps",
    "My sponsor helps", "Community keeps me accountable",
]

meaningful_health = [
    "I was just diagnosed with cancer", "The prognosis is uncertain",
    "I'm starting treatment", "Chemo is rough",
    "Radiation is exhausting", "I lost my hair",
    "I barely recognize myself", "I'm fighting for my life",
    "The fear is constant", "I'm trying to stay positive",
    "Some days I can't", "I'm allowed to be scared",
    "I'm in remission", "The relief is overwhelming",
    "But the fear of recurrence", "Every scan is terrifying",
    "I don't take time for granted anymore", "Cancer changed my perspective",
    "I have a chronic condition", "It's not going away",
    "I manage it daily", "Some days are better",
    "Some days I can barely function", "I've had to adjust my life",
    "I can't do what I used to", "I've mourned that version of me",
    "I have autoimmune disease", "My body attacks itself",
    "Flares are unpredictable", "I never know how I'll feel",
    "I've had to cancel a lot", "People stopped inviting me",
    "I have diabetes", "Managing blood sugar is constant",
    "I have heart disease", "I had a heart attack",
    "I almost died", "Second chance at life",
    "I'm making changes", "I have to take better care",
    "I ignored warning signs", "I didn't prioritize my health",
    "I have epilepsy", "Seizures are scary",
    "I never know when one will hit", "I can't drive",
    "I have fibromyalgia", "The pain is constant",
    "Everything hurts", "People don't see pain",
    "I have chronic fatigue", "Tired doesn't cover it",
    "Sleep doesn't help", "I wake up exhausted",
    "I push through anyway", "I have long covid",
    "Brain fog is debilitating", "I forget words",
    "I was sharp before", "I grieve my old brain",
    "I had surgery", "Recovery is slow",
    "My body needs time", "I'm impatient with myself",
    "I had a stroke", "I'm relearning things",
    "Rehabilitation is hard work", "Small victories matter",
    "I have an eating disorder", "My relationship with food is complicated",
    "Recovery isn't linear", "I've been in treatment",
    "I still struggle some days", "The thoughts don't fully go away",
    "I have chronic pain", "Pain is my constant companion",
    "I've learned to live with it", "Some days it wins",
    "Pain changes you", "I have migraines",
    "They're debilitating", "I lose days",
    "I have endometriosis", "The pain is severe",
    "Doctors dismissed me for years", "I knew something was wrong",
    "I had to advocate hard", "The diagnosis was validating",
    "It affects fertility", "I don't know if I can have kids",
    "I had a miscarriage", "We lost the baby",
    "The grief is overwhelming", "People don't know what to say",
    "I'm struggling with infertility", "We've been trying for years",
    "Each month is disappointment", "IVF is hard",
    "I'm pregnant and scared", "This wasn't planned",
    "I don't know what to do", "I'm weighing my options",
    "I had an abortion", "It was the right choice for me",
    "I'm postpartum and struggling", "This isn't what I expected",
    "PPD is real", "I need help",
]

meaningful_work = [
    "I got fired", "I was laid off",
    "I didn't see it coming", "My identity was tied to that job",
    "I don't know who I am without work", "The job market is brutal",
    "I've applied to hundreds of jobs", "The rejection is demoralizing",
    "I'm running out of savings", "I'm scared about money",
    "I might lose my home", "I'm one paycheck away from disaster",
    "I hate my job", "I dread going to work",
    "Sunday scaries are real", "I cry in the parking lot",
    "I dissociate at my desk", "Golden handcuffs are real",
    "I can't afford to leave", "Healthcare ties me here",
    "I dream of quitting", "I'm making an exit plan",
    "I'm burned out from work", "I've given everything",
    "I'm exploited", "Underpaid and overworked",
    "My boss is toxic", "The workplace is hostile",
    "I'm being harassed", "I'm being discriminated against",
    "I've documented everything", "HR isn't helping",
    "HR protects the company", "I'm considering legal action",
    "I'm scared of retaliation", "I've been retaliated against",
    "For speaking up", "I did the right thing",
    "Even though it cost me", "I'm starting my own business",
    "Taking the leap is terrifying", "I believe in this idea",
    "I'm betting on myself", "For the first time",
    "I might fail", "Failure is information",
    "I'm changing careers", "Starting over at this age",
    "People think I'm crazy", "But I'm unhappy staying",
    "Life's too short", "I want meaningful work",
    "I want to make a difference", "I'm pursuing my passion",
    "I put it off for decades", "I'm doing it now",
    "I went back to school", "I'm the oldest in my class",
    "I got promoted", "I worked so hard for this",
    "Imposter syndrome said don't", "I did anyway",
    "I belong here", "I'm still convincing myself",
    "I'm in over my head", "I'll figure it out",
]

meaningful_struggles = [
    "I'm drowning in debt", "I don't know how to get out",
    "The interest keeps compounding", "I'm ashamed of my finances",
    "I was never taught about money", "I'm considering bankruptcy",
    "I'm fighting an addiction", "The escape is the same",
    "I'm in legal trouble", "I made a mistake",
    "I'm facing consequences", "I'm taking responsibility",
    "I have a record now", "That follows me",
    "Opportunities are limited", "I'm rebuilding my life",
    "Second chances are hard to find", "I'm in an abusive situation",
    "I can't leave yet", "It's complicated",
    "I'm making a plan", "I'm building resources",
    "I'm being careful", "I left an abusive relationship",
    "Getting out was hard", "Staying out is hard too",
    "Trauma bonding is real", "I'm homeless",
    "I'm housing insecure", "I don't know where I'll sleep",
    "I'm fighting to survive", "Every day is a battle",
    "I'm facing eviction", "I might lose my home",
    "I have kids to think about", "I'm caring for someone sick",
    "Caregiver burnout is real", "I need respite",
    "There's no one else", "I'm watching them decline",
    "Anticipatory grief is brutal", "I'm dealing with a stalker",
    "I don't feel safe", "I've changed my routine",
    "The police aren't helpful", "I'm hypervigilant constantly",
    "I was in an accident", "I almost died",
    "Life flashed before my eyes", "Recovery is long",
    "PTSD from it is real", "I'm different now",
    "I witnessed something traumatic", "I can't unsee it",
    "It haunts me", "I see it when I close my eyes",
    "I survived a natural disaster", "Lost everything",
    "Rebuilding from nothing", "I'm dealing with betrayal",
    "Someone I trusted completely", "Broke that trust completely",
    "I question everyone now", "I was scammed",
    "I lost a lot of money", "I feel stupid",
    "I was falsely accused", "My reputation was damaged",
    "I'm struggling with my faith", "Questions I can't answer",
    "Deconstruction is painful", "My whole worldview is shifting",
    "I left my religion", "I lost community",
    "Some people shun me now", "But I'm free",
    "I can think for myself", "I can be myself",
    "I'm enough", "Just as I am",
    "I'm finally believing that", "After all these years",
]

meaningful_goals = [
    "I'm finally pursuing my dream", "I've wanted this my whole life",
    "I was told it wasn't practical", "I'm going for it",
    "I'm writing a book", "I'm making an album",
    "I'm creating art", "I'm building something",
    "Something that matters to me", "Maybe no one will care",
    "I care", "That has to be enough",
    "I'm training for something big", "Pushing my limits",
    "I didn't think I could", "I'm proving myself wrong",
    "I'm learning a new skill", "It's hard and humbling",
    "Being a beginner again", "But growth requires it",
    "I'm saving for something important", "Sacrificing now for later",
    "The goal matters", "I'm working toward it daily",
    "I'm planning a big change", "Moving somewhere new",
    "Starting fresh", "I've outgrown this place",
    "I'm trying to get healthy", "Really trying this time",
    "This time feels different", "It's not about appearance",
    "It's about feeling good", "Living longer for my kids",
    "I'm trying to be a better person", "I've made mistakes",
    "I've hurt people", "I'm trying to make amends",
    "I'm learning from the past", "Not repeating it",
    "Growth is possible", "I'm working on my legacy",
    "What I'll leave behind", "Impact",
    "How I made people feel", "I want my life to matter",
    "I'm making it matter", "One day at a time",
    "I'm becoming who I was meant to be", "Finally",
]

# Add all meaningful to the list
for item in meaningful_emotional:
    MASSIVE_TEST_CASES.append((item, "persist"))
for item in meaningful_family:
    MASSIVE_TEST_CASES.append((item, "persist"))
for item in meaningful_identity:
    MASSIVE_TEST_CASES.append((item, "persist"))
for item in meaningful_health:
    MASSIVE_TEST_CASES.append((item, "persist"))
for item in meaningful_work:
    MASSIVE_TEST_CASES.append((item, "persist"))
for item in meaningful_struggles:
    MASSIVE_TEST_CASES.append((item, "persist"))
for item in meaningful_goals:
    MASSIVE_TEST_CASES.append((item, "persist"))


def run_massive_stress_test():
    """Run the massive stress test against the classifier"""
    from classifier_gate import predict
    
    correct = 0
    false_positives = []
    false_negatives = []
    
    print("=" * 70)
    print("MASSIVE STRESS TEST")
    print("=" * 70)
    
    total = len(MASSIVE_TEST_CASES)
    trivial_count = sum(1 for _, e in MASSIVE_TEST_CASES if e == "flush")
    meaningful_count = sum(1 for _, e in MASSIVE_TEST_CASES if e == "persist")
    
    print(f"Total examples: {total}")
    print(f"Trivial (should flush): {trivial_count}")
    print(f"Meaningful (should persist): {meaningful_count}")
    print(f"\nRunning...")
    
    for i, (exchange, expected) in enumerate(MASSIVE_TEST_CASES):
        if (i + 1) % 500 == 0:
            print(f"  Progress: {i + 1}/{total}")
        
        # Use default threshold (0.50)
        prediction, confidence = predict(exchange)
        predicted = prediction.lower()
        
        if predicted == expected:
            correct += 1
        else:
            if expected == "persist" and predicted == "flush":
                false_positives.append((exchange, confidence))
            else:
                false_negatives.append((exchange, confidence))
    
    accuracy = correct / total
    
    print(f"\n{'=' * 70}")
    print("RESULTS")
    print("=" * 70)
    print(f"Accuracy: {correct}/{total} = {accuracy:.1%}")
    print(f"False Positives (lost memories): {len(false_positives)}")
    print(f"False Negatives (noise persisted): {len(false_negatives)}")
    
    if false_positives:
        print(f"\n{'=' * 70}")
        print(f"FALSE POSITIVES — Should PERSIST, got flushed (CRITICAL)")
        print(f"Showing first 20:")
        print("=" * 70)
        for ex, conf in false_positives[:20]:
            print(f"  [{conf:.2f}] {ex[:65]}...")
    
    if false_negatives:
        print(f"\n{'=' * 70}")
        print(f"FALSE NEGATIVES — Should FLUSH, got persisted")
        print(f"Showing first 20:")
        print("=" * 70)
        for ex, conf in false_negatives[:20]:
            print(f"  [{conf:.2f}] {ex[:65]}...")
    
    print(f"\n{'=' * 70}")
    print("SUMMARY")
    print("=" * 70)
    
    if accuracy >= 0.95:
        print("✓ EXCELLENT — Gate is production-ready")
    elif accuracy >= 0.90:
        print("~ GOOD — Gate is robust with edge cases")
    elif accuracy >= 0.85:
        print("! FAIR — Gate needs more training data")
    else:
        print("✗ NEEDS WORK — Gate requires revision")
    
    return accuracy, false_positives, false_negatives


if __name__ == "__main__":
    run_massive_stress_test()
